config/routes.rb
Rails.application.routes.draw do
  resources :pathfinders
  resources :units
  resources :counselors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/counselor.rb
class Counselor < ApplicationRecord

    def full_name
        self.name + " " + self.last_name
    end
end

app/models/pathfinder.rb
class Pathfinder < ApplicationRecord
  belongs_to :unit

  def full_name
    self.name + " " + self.last_name
  end
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :counselor
  has_many :pathfinders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/counselors_controller.rb
class CounselorsController < ApplicationController
  before_action :set_counselor, only: [:show, :edit, :update, :destroy]

  # GET /counselors
  # GET /counselors.json
  def index
    @counselors = Counselor.all
  end

  # GET /counselors/1
  # GET /counselors/1.json
  def show
  end

  # GET /counselors/new
  def new
    @counselor = Counselor.new
  end

  # GET /counselors/1/edit
  def edit
  end

  # POST /counselors
  # POST /counselors.json
  def create
    @counselor = Counselor.new(counselor_params)

    respond_to do |format|
      if @counselor.save
        format.html { redirect_to @counselor, notice: 'Counselor was successfully created.' }
        format.json { render :show, status: :created, location: @counselor }
      else
        format.html { render :new }
        format.json { render json: @counselor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /counselors/1
  # PATCH/PUT /counselors/1.json
  def update
    respond_to do |format|
      if @counselor.update(counselor_params)
        format.html { redirect_to @counselor, notice: 'Counselor was successfully updated.' }
        format.json { render :show, status: :ok, location: @counselor }
      else
        format.html { render :edit }
        format.json { render json: @counselor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /counselors/1
  # DELETE /counselors/1.json
  def destroy
    @counselor.destroy
    respond_to do |format|
      format.html { redirect_to counselors_url, notice: 'Counselor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_counselor
      @counselor = Counselor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def counselor_params
      params.require(:counselor).permit(:name, :last_name, :dni)
    end
end

app/controllers/pathfinders_controller.rb
class PathfindersController < ApplicationController
  before_action :set_pathfinder, only: [:show, :edit, :update, :destroy]

  # GET /pathfinders
  # GET /pathfinders.json
  def index
    @pathfinders = Pathfinder.all
    @pathfinders = @pathfinders.where(:unit_id => params[:unit_id]) if params[:unit_id]
    if params[:search]
      @pathfinders = @pathfinders.where('name like ?', '%' + params[:search] + '%' )
    end
  end

  # GET /pathfinders/1
  # GET /pathfinders/1.json
  def show
  end

  # GET /pathfinders/new
  def new
    @pathfinder = Pathfinder.new
  end

  # GET /pathfinders/1/edit
  def edit
  end

  # POST /pathfinders
  # POST /pathfinders.json
  def create
    @pathfinder = Pathfinder.new(pathfinder_params)

    respond_to do |format|
      if @pathfinder.save
        format.html { redirect_to @pathfinder, notice: 'Pathfinder was successfully created.' }
        format.json { render :show, status: :created, location: @pathfinder }
      else
        format.html { render :new }
        format.json { render json: @pathfinder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pathfinders/1
  # PATCH/PUT /pathfinders/1.json
  def update
    respond_to do |format|
      if @pathfinder.update(pathfinder_params)
        format.html { redirect_to @pathfinder, notice: 'Pathfinder was successfully updated.' }
        format.json { render :show, status: :ok, location: @pathfinder }
      else
        format.html { render :edit }
        format.json { render json: @pathfinder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pathfinders/1
  # DELETE /pathfinders/1.json
  def destroy
    @pathfinder.destroy
    respond_to do |format|
      format.html { redirect_to pathfinders_url, notice: 'Pathfinder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pathfinder
      @pathfinder = Pathfinder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pathfinder_params
      params.require(:pathfinder).permit(:name, :last_name, :birthday, :dni, :unit_id)
    end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    if @unit.pathfinders.any?
      respond_to do |format|
        format.html { redirect_to units_url, notice: 'Esa unidad tiene conquistadores, eliminelos antes de borrarla.' }
        format.json { head :no_content }
      end
    else
      @unit.destroy
      respond_to do |format|
        format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :counselor_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counselors_helper.rb
module CounselorsHelper
end

app/helpers/pathfinders_helper.rb
module PathfindersHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/counselors/_form.html.erb
<%= form_with(model: counselor, local: true) do |form| %>
  <% if counselor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(counselor.errors.count, "error") %> prohibited this counselor from being saved:</h2>

      <ul>
      <% counselor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, {:class=>"form-control"} %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, {:class=>"form-control"} %>
  </div>

  <div class="field">
    <%= form.label :dni %>
    <%= form.number_field :dni, {:class=>"form-control"} %>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar Consejero', {:class=>"btn btn-primary"} %>
  </div>
<% end %>

app/views/counselors/edit.html.erb
<h1>Editing Counselor</h1>

<%= render 'form', counselor: @counselor %>

<%= link_to 'Show', @counselor %> |
<%= link_to 'Back', counselors_path %>

app/views/counselors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Counselors</h1>

<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Last name</th>
      <th scope="col">Dni</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @counselors.each do |counselor| %>
      <tr>
        <td scope="row"><%= counselor.name %></td>
        <td><%= counselor.last_name %></td>
        <td><%= counselor.dni %></td>
        <td><%= link_to 'Show', counselor %></td>
        <td><%= link_to 'Edit', edit_counselor_path(counselor) %></td>
        <td><%= link_to 'Destroy', counselor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Consejero', new_counselor_path, { :class=>"btn btn-primary btn-lg active"} %>

app/views/counselors/new.html.erb
<h1>New Counselor</h1>

<%= render 'form', counselor: @counselor %>

<%= link_to 'Back', counselors_path %>

app/views/counselors/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row justify-content-center">
    <div class="col-3 text-center">
      <div class="card text-center">
        <div class="card-header">
          <%= @counselor.full_name %>
        </div>
        <div class="card-body">
          <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <strong>Dni:</strong>
                <%= @counselor.dni %>
              </li>
          </ul>
        </div>
        <div class="card-footer text-muted">
        <div class="btn-group btn-group-lg" role="group">
          <%= link_to 'Back', counselors_path, { :class=>"btn btn-primary btn-lg active"} %>
          <%= link_to 'Edit', edit_counselor_path(@counselor) , { :class=>"btn btn-primary btn-lg active"} %>
        </div>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConquiManage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">ConquiManage</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Unidades', units_path, { :class=>"nav-link"} %>
        </li>
        <li class="nav-item">
          <%= link_to 'Conquistadores', pathfinders_path, { :class=>"nav-link"} %>
        </li>
        <li class="nav-item">
          <%= link_to 'Consejeros', counselors_path, { :class=>"nav-link"} %>
        </li>
      </ul>
      <span class="navbar-text">
        El mejor manejo de tu Club.
      </span>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pathfinders/_form.html.erb
<%= form_with(model: pathfinder, local: true) do |form| %>
    <% if pathfinder.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(pathfinder.errors.count, "error") %> prohibited this pathfinder from being saved:</h2>

        <ul>
        <% pathfinder.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, {:class=>"form-control"} %>
  </div>
  <div class="form-group">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, {:class=>"form-control"} %>
  </div>

  <div class="form-group">
      <%= form.label :birthday %>
      <%= form.datetime_select :birthday, {:class=>"form-control"} %>
    </div>

    <div class="form-group">
      <%= form.label :dni %>
      <%= form.number_field :dni, {:class=>"form-control"} %>
    </div>

    <div class="form-group">
      <%= form.label :unit_id %>
      <%= collection_select(:pathfinder, :unit_id, Unit.all, :id, :name, {:class=>"form-control"}) %>
    </div>
    <%= form.submit 'Guardar Conquistador', {:class=>"btn btn-primary"} %>
<% end %>

app/views/pathfinders/edit.html.erb
<h1>Editing Pathfinder</h1>

<%= render 'form', pathfinder: @pathfinder %>

<%= link_to 'Show', @pathfinder %> |
<%= link_to 'Back', pathfinders_path %>

app/views/pathfinders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pathfinders</h1>
<form method="get" class="form-inline">
  <div class="form-group mx-sm-3 mb-2">
    <label for="inputPassword2" class="sr-only">Buscar</label>
    <input type="text" name="search" class="form-control" id="inputPassword2" placeholder="Buscar...">
  </div>
  <button type="submit" class="btn btn-primary mb-2">Buscar</button>
</form>

<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Last name</th>
      <th>Birthday</th>
      <th>Dni</th>
      <th>Unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pathfinders.each do |pathfinder| %>
      <tr>
        <td scope="row"><%= pathfinder.name %></td>
        <td><%= pathfinder.last_name %></td>
        <td><%= pathfinder.birthday %></td>
        <td><%= pathfinder.dni %></td>
        <td><%= pathfinder.unit.name %></td>
        <td><%= link_to 'Show', pathfinder %></td>
        <td><%= link_to 'Edit', edit_pathfinder_path(pathfinder) %></td>
        <td><%= link_to 'Destroy', pathfinder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Conquistador', new_pathfinder_path, { :class=>"btn btn-primary btn-lg active"} %>

app/views/pathfinders/new.html.erb
<h1>New Pathfinder</h1>

<%= render 'form', pathfinder: @pathfinder %>

<%= link_to 'Back', pathfinders_path %>

app/views/pathfinders/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row justify-content-center">
    <div class="col-3 text-center">
      <div class="card text-center">
        <div class="card-header">
          <%= @pathfinder.name %>
        </div>
        <div class="card-body">
          <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <strong>Last name:</strong>
                <%= @pathfinder.last_name %>
              </li>

              <li class="list-group-item">
                <strong>Birthday:</strong>
                <%= @pathfinder.birthday %>
              </li>

              <li class="list-group-item">
                <strong>Dni:</strong>
                <%= @pathfinder.dni %>
              </li>

              <li class="list-group-item">
                <strong>Unit:</strong>
                <%= @pathfinder.unit.name %>
              </li>
          </ul>
        </div>
        <div class="card-footer text-muted">
        <div class="btn-group btn-group-lg" role="group">
          <%= link_to 'Back', pathfinders_path, { :class=>"btn btn-primary btn-lg active"} %>
          <%= link_to 'Edit', edit_pathfinder_path(@pathfinder), { :class=>"btn btn-primary btn-lg active"} %>
        </div>
      </div>
    </div>
</div>

app/views/units/_form.html.erb
<%= form_with(model: unit, local: true) do |form| %>
  <% if unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, {:class=>"form-control"} %>
  </div>

  <div class="form-group">
    <%= form.label :counselor_id %>
    <%= collection_select(:unit, :counselor_id, Counselor.all, :id, :full_name, {:class=>"form-control"}) %>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar Unidad', {:class=>"btn btn-primary"} %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editar Unidad</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Units</h1>

<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Counselor</th>
      <th>Cantidad de Conquistadores</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td scope="row"><%= unit.name %></td>
        <td><%= unit.counselor.full_name %></td>
        <td><%= link_to unit.pathfinders.count, pathfinders_path(:unit_id => unit.id) %></td>
        <td><%= link_to 'Show', unit %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Unidad', new_unit_path, { :class=>"btn btn-primary btn-lg active"} %>

app/views/units/new.html.erb
<h1>New Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row justify-content-center">
    <div class="col-3 text-center">
      <div class="card text-center">
        <div class="card-header">
          Unidad: <%= @unit.name %>
        </div>
        <div class="card-body">
          <ul class="list-group list-group-flush">
            <% @unit.pathfinders.each do |pathfinder| %>
              <li class="list-group-item"><%= pathfinder.full_name %></li>
            <% end %>
          </ul>
        </div>
        <div class="card-footer text-muted">
        <div class="btn-group btn-group-lg" role="group">
          <%= link_to 'Back', units_path, { :class=>"btn btn-primary btn-lg active"} %>
          <%= link_to 'Edit', edit_unit_path(@unit), { :class=>"btn btn-primary btn-lg active"} %>
        </div>
      </div>
    </div>
</div>